 version: 2
 jobs:
   bobby:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "A first hello world"
   ricky:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "Double trouble here we come"

 workflows:
   version: 2
   bobby_sally:
     jobs:
       - bobby
       - rickyruby
